# 关闭 Anime4K
CTRL+0 change-list glsl-shaders clr ""

# 轻量模式
CTRL+1 change-list glsl-shaders set "~~/shaders/glsl/Upscale/Anime4K_Upscale_CNN_x2_S.glsl"

# 推荐模式
CTRL+2 change-list glsl-shaders set "~~/shaders/glsl/Restore/Anime4K_Restore_CNN_M.glsl:~~/shaders/glsl/Upscale/Anime4K_Upscale_CNN_x2_M.glsl"

# 极致模式（默认）
CTRL+3 change-list glsl-shaders set "~~/shaders/glsl/Deblur/Anime4K_Deblur_DoG.glsl:~~/shaders/glsl/Restore/Anime4K_Restore_CNN_L.glsl:~~/shaders/glsl/Upscale/Anime4K_Upscale_CNN_x2_L.glsl"


#插帧开启，参数见rife.vpy
CTRL+` vf toggle vapoursynth=~/.config/mpv/rife.vpy


# 右键菜单模拟（例如按右键并按快捷键）
MOUSE_BTN3 script-binding play_from_clipboard"

